// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdontoAPI.Data;

#nullable disable

namespace OdontoAPI.Migrations
{
    [DbContext(typeof(FormaPgtoContext))]
    [Migration("20230604041424_criandoTabelaFormaPgto")]
    partial class criandoTabelaFormaPgto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OdontoAPI.Models.FormaPgto", b =>
                {
                    b.Property<int>("IdFormaDePagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Taxa")
                        .HasColumnType("double");

                    b.HasKey("IdFormaDePagamento");

                    b.ToTable("FormasPgtos");
                });
#pragma warning restore 612, 618
        }
    }
}
